services:
 backend:
  build:
   context: ./backend
   dockerfile: ./Dockerfile
  image: 'ntnui/opptak-backend'
  ports:
   - '8082:8082'
 frontend:
  build:
   context: ./frontend
   dockerfile: ./Dockerfile
  image: 'ntnui/opptak-frontend'
  ports:
   - '3000:3000'
  links:
   - 'backend:be'
